### ISSUE TITLE
blink examples bug

### ISSUE THREAD

**Issue by wjsvec** [milkv-duo/duo-examples#2]
As shown in the figure, the LED pin is 0
![image](https://github.com/milkv-duo/duo-examples/assets/39830125/4154ed4d-c221-4169-916f-d7a652c11eca)

And in the example code, the GUO_LED is 25
![image](https://github.com/milkv-duo/duo-examples/assets/39830125/6671736e-ea57-48e8-b09a-a081ce6113ed)

I try this code, it's NOT work. After changing it to 0, it can run normally.

**Comment by carbonfix** [comment]
Sorry for the trouble.

The pin number of the LED pin is indeed 25.

It's because we haven't synchronized the SDK. Please follow the steps below to resolve it

1.  Use the lastest fireware [V1.0.5](https://github.com/milkv-duo/duo-buildroot-sdk/releases)
2.  Execute the 'git pull' command in the 'duo-examples' repository to the latest version
3.  Delete the 'duo-sdk' directory in the 'duo-examples' repository
4.  Execute `source envsetup.sh` again to download the updated SDK, than rebuild your app

The wiringX pin numbers is [here](https://milkv.io/docs/duo/application-development/wiringx)
